//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportGit.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Count_tickets
    {
        public int IDFlight { get; set; }
        public Nullable<int> CountSeats { get; set; }
        public Nullable<int> Count_tickets1 { get; set; }
        public Nullable<int> Ostatok { get; set; }
    }
}
