//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AirportGit.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int IDTicket { get; set; }
        public Nullable<System.DateTime> DateOfBuy { get; set; }
        public Nullable<int> IDClassReservation { get; set; }
        public Nullable<int> IDFlight { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> IDClient { get; set; }
        public Nullable<int> IDBaggage { get; set; }
    
        public virtual Baggage Baggage { get; set; }
        public virtual ClassReservation ClassReservation { get; set; }
        public virtual Client Client { get; set; }
        public virtual Flight Flight { get; set; }
    }
}
